[package]
name = "veronymous-client-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "veronymous_client",
    "veronymous-client-cli",
    "veronymous-client-jni"
]